# Generated by Django 5.2.4 on 2025-07-22 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='expires_in_minutes',
            new_name='expires_in_seconds',
        ),
    ]
