# Generated by Django 5.2.4 on 2025-07-22 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_rename_expires_in_minutes_note_expires_in_seconds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='expires_in_seconds',
        ),
        migrations.RemoveField(
            model_name='note',
            name='title',
        ),
    ]
